version: 2.1

jobs:
  build:
    docker:
      - image: afreeorange/build:latest

    steps:
      - checkout

      - run:
          name: Building excuses 😂
          command: npm run build:excuses

      - run:
          name: Building site
          command: npm run build

      - run:
          name: Deploying ☝️
          command: |-
            find ./dist/ -type f -exec gzip "{}" \; -exec mv "{}.gz" "{}" \;
            aws s3 sync --exclude='manifest*.webmanifest' --delete --content-encoding 'gzip' dist/ s3://sorry.nikhil.io/
            aws s3 sync --exclude='*' --include='manifest*.webmanifest' --content-encoding 'gzip' --content-type 'application/manifest+json' dist/ s3://sorry.nikhil.io/
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths '/index.html'
