version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - aws-cli/install
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Sample MD5
          command: echo "COME ON" | md5sum

      - run:
          name: Deploy to S3
          command: ./deploy
