version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - aws-cli/install
      - checkout
      - run:
          name: Building excuses, lol
          command: ./.circleci/build
      - run:
          name: Deploying to S3
          command: ./.circleci/deploy

  github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - run:
          name: Trying Github
          command: ls -l ./
