version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Building excuses, lol
          command: ./.circleci/build
      - persist_to_workspace:
          root: ./
          paths: ./*

  github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Releasing to GitHub
          command: ./.circleci/release
      - persist_to_workspace:
          root: ./
          paths: ./*

  aws-deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/install
      - run:
          name: Deploying to AWS
          command: ./.circleci/deploy

workflows:
  version: 2.1

  build-and-release:
    jobs:
      - build
      - github-release:
          requires:
            - build
      - aws-deploy:
          requires:
            - github-release
