version: 2.1

jobs:
  build:
    docker:
      - image: afreeorange/build:latest

    steps:
      - checkout

      - run:
          name: Building excuses 😂
          command: node .scripts/build.js

      - run:
          name: Building site
          command: |-
            parcel build src/index.html
            mv excuses.json dist/

      - run:
          name: Deploying ☝️
          command: |-
            find ./dist/ -type f -exec gzip "{}" \; -exec mv "{}.gz" "{}" \;
            aws s3 sync --delete --content-encoding 'gzip' dist/ s3://sorry.nikhil.io/
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths '/index.html'
