version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - aws-cli/install
      - checkout
      - run:
          name: Building excuses, lol
          command: ./.circleci/build
      - persist_to_workspace:
          root: .
          paths: sorry.nikhil.io/*
      - run:
          name: Deploying to S3
          command: ./.circleci/deploy

  github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Trying Github
          command: ls -l /workspace/ && env

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - build
      - github-release:
          requires:
            - build
